### ISSUE TITLE
Gem takeover

### ISSUE THREAD

**Issue by hmdne** [opal/paggio#7]
Hi @meh

I noticed you are inactive in opal project recently. Due to my recent changes to opal-browser I need to deploy some minor changes to this gem and release a new version. I think the best course of action would be for me to take it over, or maybe it can be moved to @opal (ping: @elia). In any case, I'm active on opal's Slack channel.

**Comment by meh** [comment]
Any way is fine by me.

**Comment by elia** [comment]
@meh can you please handle the transfer or give me admin access to paggio so I can do it?

**Comment by elia** [comment]
@meh can you make me repo admin? otherwise I can't move it

**Comment by meh** [comment]
Yup, just let me get to the studio.

**Comment by meh** [comment]
Wait, how the hell do I do that?

**Comment by elia** [comment]
hmmmm, I think it's easier to just transfer ownership at this point 
<img width="861" alt="image" src="https://user-images.githubusercontent.com/1051/118689247-144ffb80-b807-11eb-866f-79df48e8a351.png">

**Comment by hmdne** [comment]
Please make sure to also exchange the gem publishing credentials

**Comment by hmdne** [comment]
Hi again :D 

@meh It's been 2 years now since I taken on development of opal-browser and I'd like to make a release soon. To do it, we will need the following:

* https://rubygems.org/gems/opal-browser/owners
* https://rubygems.org/gems/paggio/owners

Could you add me (hmdne) and elia (elia) to the owner list on the pages I sent you above? Then, for paggio, as elia said, we'd be glad if you transfered ownership of this repository to the `opal` organization. That would be all.

**Comment by hmdne** [comment]
This is solved now. Thank you, @meh !
